export const groupTypes = {
    GET_GROUP: "GET_GROUP",
    SAVE_GROUP: "SAVE_GROUP",
    UPDATE_GROUP: "UPDATE_GROUP",
    NON_GROUP_MEMBERS:"NON_GROUP_MEMBERS",
    GET_GROUP_BY_ID:"GET_GROUP_BY_ID"
}