export const userTypes ={
    AUTHENTICATE: "AUTHENTICATE",
    RESET_STORE:"RESET_STORE",
    CREATE_USER:"CREATE_USER",
    EDIT_USER:"EDIT_USER",
    LIST_USER:"LIST_USER",
    GET_USER_BY_ID:"GET_USER_BY_ID"
}